$ANSIBLE_VAULT;1.1;AES256
36343130303662643036616638343431663364366130386330393865643266656330666632623434
6339633933306661383836323933663237383939393361340a343135316633326437643263376234
33353166303432313337363439363932376536666366383835666137303664653237386537383531
6366383034376664650a646433366462333366643733653266643134383533613130383131333765
31366331393863643363613932643364343138303161313330643139613637656537666239343661
36646330326339343066366132373966376230346337303430343662303939623230333936346664
37333534363132393363666230316237313466643030306638383237356532663235646164663532
65623731363131643530353963613330303039353432336230613734656436343238346633303465
31313631323334326361386232306465376638613863353236646439623263333336323762393737
34653565343330663865343462666233373237393437633135346366646631656363646362666665
61373762316664303466373065636136623762633564616239333963376665646135303034376435
63613764306136616238396262313138396435313264313664343864353537333862316137393230
61613763363532313239646266326337643163313637643936393438636466636437633338656136
3661373134383064353630343865356565353835333566313862
